name: Lint HTML & CSS

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installer Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610
        with:
          node-version: '18'
      - run: npm install --ignore-scripts
      - name: Grant execution permissions
        run: chmod +x ./node_modules/.bin/htmlhint
      - run: npm run lint:html
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@0303d6b62e310685c0e34d0b9cde218036885c4d
        env:
          SONAR_TOKEN: ${{ secrets.TOKEN_LAFLEUR_DEVOPS }}
